spring:
  jwt:
    secretKey: vmfhwprxm

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      format_sql: true
      ddl-auto: create-drop


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://myboard-database2.cs4usf0xv8ru.ap-northeast-2.rds.amazonaws.com:3306/myboard_db
    username: admin
    password: DDolchu0410!

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  redis:
    host: 0.0.0.0
    port: 6379

  social:
    kakao:
      client_id: 6c59b4dda916bc7b5a99d658afc58a07
      redirect: http://localhost:8080/login/oauth2/code/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: https://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me

    google:
      client_id: 510126896636-njlsscvepmc3bt5tv7prta6i4o1361ei.apps.googleusercontent.com
      client_secret: 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
      redirect: http://localhost:8080/login/oauth2/code/google
      url:
        login: https://accounts.google.com/o/oauth2/v2/auth
        token: https://oauth2.googleapis.com/token
        profile: https://www.googleapis.com/oauth2/v3/userinfo

    naver:
      client_id:
      client_secret:
      redirect: http://localhost:8080/social/login/naver
      url:
        login: https://nid.naver.com/oauth2.0/authorize
        token: https://nid.naver.com/oauth2.0/token
        profile: https://openapi.naver.com/v1/nid/me

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 20MB